//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knockout.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Knockout.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * jQuery JavaScript Library v1.7.2
        /// * http://jquery.com/
        /// *
        /// * Copyright 2011, John Resig
        /// * Dual licensed under the MIT or GPL Version 2 licenses.
        /// * http://jquery.org/license
        /// *
        /// * Includes Sizzle.js
        /// * http://sizzlejs.com/
        /// * Copyright 2011, The Dojo Foundation
        /// * Released under the MIT, BSD, and GPL Licenses.
        /// *
        /// * Date: Wed Mar 21 12:46:34 2012 -0700
        /// */
        /////(function( window, undefined ) {
        ///
        ///// Use the correct document accordingly with window argument (sandbox)
        ///var document = windo [rest of string was truncated]&quot;;.
        /// </summary>
        public static string jquery {
            get {
                return ResourceManager.GetString("jquery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Knockout JavaScript library v2.0.0
        ///// (c) Steven Sanderson - http://knockoutjs.com/
        ///// License: MIT (http://www.opensource.org/licenses/mit-license.php)
        ///
        ///var ko = {};
        ///// Google Closure Compiler helpers (used only to make the minified file smaller)
        ///ko.exportSymbol = function(publicPath, object) {
        ///	var tokens = publicPath.split(&quot;.&quot;);
        ///	var target = window;
        ///	for (var i = 0; i &lt; tokens.length - 1; i++)
        ///		target = target[tokens[i]];
        ///	target[tokens[tokens.length - 1]] = object;
        ///};
        ///ko.exportProperty [rest of string was truncated]&quot;;.
        /// </summary>
        public static string knockout {
            get {
                return ResourceManager.GetString("knockout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table class=&quot;ko-grid&quot;&gt;
        ///	&lt;thead&gt;
        ///		&lt;tr data-bind=&quot;foreach: columns&quot;&gt;
        ///			&lt;th data-bind=&quot;text: headerText&quot;&gt;&lt;/th&gt;
        ///		&lt;/tr&gt;
        ///	&lt;/thead&gt;
        ///	&lt;tbody data-bind=&quot;foreach: itemsOnCurrentPage&quot;&gt;
        ///		&lt;tr data-bind=&quot;foreach: $parent.columns&quot;&gt;
        ///			&lt;td data-bind=&quot;text: typeof rowText == &apos;function&apos; ? rowText($parent) : $parent[rowText]&quot;&gt;&lt;/td&gt;
        ///		&lt;/tr&gt;
        ///	&lt;/tbody&gt;
        ///&lt;/table&gt;
        ///&lt;div class=&quot;ko-grid-pageLinks&quot;&gt;
        ///	&lt;span&gt;Page:&lt;/span&gt;
        ///	&lt;!-- ko foreach: ko.utils.range(0, maxPageIndex) --&gt;
        ///	&lt;a href=&quot;#&quot; data-bind=&quot;text: $data + 1, cli [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SimpleGridView {
            get {
                return ResourceManager.GetString("SimpleGridView", resourceCulture);
            }
        }
    }
}
